require 'simctl'
default_platform(:ios)

runtime = SimCtl.runtime(name: "iOS 15.5")
devicetype = SimCtl.devicetype(name: "iPhone 11")

platform :ios do
  desc "Generate new screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "Hackers.xcworkspace", 
      scheme: "Hackers",
      override_status_bar: true
    )
    frameit(
      path: "./fastlane/screenshots/"
    )
    # upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end

  desc "Run Tests"
  lane :test do
    @device = SimCtl.create_device 'TestiPhone', devicetype, runtime
    scan(
      scheme: "HackersUITests",
      device: "TestiPhone",
      derived_data_path: "TestsData/DerivedData/",
      output_directory: "test_output/",
      result_bundle: true
    )
    device.delete
    sh("./xcresults export ../test_output/HackersUITests.xcresult ../test_output/json")
    sh("python3 ./parser.py")
  end

  desc "Run Tests with error"
  error do |lane, exception, options|
  	if lane == :test
      @device.delete
  		sh("./xcresults export ../test_output/HackersUITests.xcresult ../test_output/json")
    	sh("python3 ./parser.py")
  	end
  end

  desc "Build"
  lane :build do |options|
    xcodebuild(
      workspace: "Hackers.xcworkspace",
      scheme: "Hackers",
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      sdk: "iphonesimulator"
    )
  end

  desc "Archive"
  lane :archive do
    gym(scheme: "Hackers")
  end

  desc "Lint"
  lane :lint do
    swiftlint
  end
end
